# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    website: Aqua\WebCheckupBundle\Entity\Website

services:
    web_rank:
        class: Aqua\WebCheckupBundle\Model\WebRank
        arguments: ["@logger"]
