aqua_web_checkup_homepage:
    path:     /
    defaults: { _controller: AquaWebCheckupBundle:Default:index }

aqua_web_checkup_success:
    path:     /results
    defaults: { _controller: AquaWebCheckupBundle:Default:results }

aqua_web_checkup_about:
    path:     /about
    defaults: { _controller: AquaWebCheckupBundle:Default:about }

aqua_web_checkup_download:
    path:     /download
    defaults: { _controller: AquaWebCheckupBundle:Default:download }
