aqua_web_checkup_homepage:
    path:     /
    defaults: { _controller: AquaWebCheckupBundle:Default:index }

aqua_web_checkup_success:
    path:     /results
    defaults: { _controller: AquaWebCheckupBundle:Default:results }
